// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    return typeof console !== "undefined" && console !== null ? console.log("The main javascript file") : void 0;
  });

}).call(this);
